title: Crowd Analysis
description: Assessing pedestrian responses to autonomous and personal mobility robots in crowded public spaces
theme: jekyll-theme-primer

# Skip heavy / data folders so Pages builds fast and avoids symlinks
exclude:
  - "**/data/**"
  - "**/datasets/**"
  - ".devcontainer/**"
  - ".github/**"
  - "node_modules/**"
  - "venv/**"
  - ".venv/**"